question/urls.py
from django.conf.urls import url
from django.contrib import admin
from app01 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^add_questionnaire/$', views.add),
    url(r'^login/$', views.login),
    url(r'^edit_questionnaire/(\d+)/$', views.edit_questionnaire),
    url(r'^student/evaluate/(\d+)/(\d+)/$', views.score),

]

app01/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    '''
    员工表
    '''
    username = models.CharField(max_length=16,verbose_name="用户名")
    password = models.CharField(max_length=16,verbose_name="用户密码")

    class Meta:
        verbose_name_plural = "员工表"

    def __str__(self):
        return self.username

class Student(models.Model):
    '''
    学生表
    '''
    name = models.CharField(verbose_name="学生姓名",max_length=16)
    pwd = models.CharField(verbose_name="密码",max_length=16)
    cls = models.ForeignKey(verbose_name="所在班级",to="ClassList")

    class Meta:
        verbose_name_plural = "学生表"
    def __str__(self):
        return self.name

class ClassList(models.Model):
    '''
    班级表
    '''
    title = models.CharField(verbose_name="班级名",max_length=16)

    class Meta:
        verbose_name_plural = "班级表"
    def __str__(self):
        return self.title

class Questionnaire(models.Model):
    '''
    问卷表
    '''
    title = models.CharField(verbose_name="问卷标题",max_length=128)
    cls = models.ForeignKey(verbose_name="调查班级",to="ClassList")
    creator = models.ForeignKey(verbose_name="创建者",to="UserInfo")
    stu_num = models.IntegerField(verbose_name="参与人数",default=0)



    class Meta:
        verbose_name_plural = "问卷表"

    def __str__(self):
        return self.title

class Question(models.Model):
    '''
    问题表
    '''
    caption = models.CharField(verbose_name="问题标题",max_length=64)
    question_type = (
        (1,"打分"),
        (2,"单选"),
        (3,"评价"),
    )
    ct = models.IntegerField(choices=question_type)
    questionnaire = models.ForeignKey(to="Questionnaire")

    class Meta:
        verbose_name_plural = "问题表"
    def __str__(self):
        return self.caption

class Option(models.Model):
    '''
   单选题的选项
    '''
    name = models.CharField(verbose_name="选项名称",max_length=32)
    score = models.IntegerField(verbose_name="选项对应的分值")
    question = models.ForeignKey(to="Question")

    class Meta:
        verbose_name_plural = "单选题的选项"
    def __str__(self):
        return self.name

class Answer(models.Model):
    '''
    答案
    '''
    user = models.ForeignKey(to="Student",verbose_name="谁回答的")
    question = models.ForeignKey(to='Question',verbose_name="问题")


    content = models.CharField(verbose_name="答案内容",max_length=255,null=True,blank=True)
    option = models.ForeignKey(to="Option",null=True,blank=True)
    val = models.IntegerField(null=True,blank=True)

    class Meta:
        verbose_name_plural = "答案表"

templates/add.html
{% extends 'base.html' %}
 
{% block page_title %}
添加问卷
{% endblock %}
{% block content %}
    <div class="panel-body ">
    <form method="post" novalidate>
    {% csrf_token %}
            <div class="row">
    <p class="col-md-6"><span>问卷标题：{{ form.title }}{{ form.errors.title.0 }}</span></p>
    </div>
    <div class="row">
    <p class="col-md-3">问卷班级：{{ form.cls }}{{ form.errors.cls.0 }}</p>
    </div>

    <button class="btn btn-primary" type="submit">提交</button>

    </form>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/edit_questionnaire.css">
    <script src="/static/js/jquery-3.2.1.min.js"></script>
    <script src="/static/js/jquery.cookie.js"></script>

</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    菜单列表
                </div>

            </div>
        </div>
        <div class="col-md-10">
            <div class="panel panel-default">
                <div class="panel-heading"><a href="/">首页</a>/{% block page_title %}{% endblock %}</div>
            {% block content %}
            {% endblock %}
            </div>
        </div>


    </div>

</div>

<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/edit_ques.js"></script>
</body>
</html>

templates/edit_questionnaire.html
{% extends 'base.html' %}

{% block page_title %}
    编辑问卷
{% endblock %}

{% block content %}
    <div class="panel panel-body edit_ques">
    <p class="btn_style">
        <button class="btn btn-success add_question ">添加</button>
        &nbsp;&nbsp;
        <button class="btn btn-primary btn_save">保存</button>
    </p>
    <ol class="question_list">
        <form class="form-horizontal" method="post" novalidate>
        {% csrf_token %}
            {% for item in form_list %}
                <li>
                    <div pk="{{ item.obj.id }}" class="pk">
                        <div class="form-group">
                            <label for="id_caption" class="col-md-2 control-label">问题名称：</label>
                            <div class="col-md-10">
                                {{ item.form.caption }}{{ item.form.errors.caption.0 }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_ct" class="col-md-2 control-label">问题类型：</label>
                            <div class="col-md-3 add_btn">
                                {{ item.form.ct }}
                            </div>
                            <div class="col -md-2">
                                <span style="font-size: 20px" class="add_choice"><a href="#add_choice" class="{{ item.options_cls }}">✚添加选项</a></span>
                            </div>
                        </div>
                        <ul class="choice_list">
                            {% for v in item.options %}
                                <div id="{{ v.obj.id }}">
                                    <div class="row col-md-10">
                                        <label for="id_name" class="col-md-2 control-label">●&nbsp;内容：</label>
                                        <div class="col-md-3">
                                            {{ v.form.name }}
                                        </div>
                                        <label for="id_score" class="col-md-2 control-label">分值：</label>
                                        <div class="col-md-3">
                                            {{ v.form.score }}
                                        </div>
                                        <label class="col_fork">×</label>
                                    </div>
                                </div>
                            {% endfor %}
                        </ul>
                        <span class="fork">×</span>
                    </div>
                </li>
            {% endfor %}
        </form>
    </ol>
    </div>


{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block page_title %}
问卷列表
{% endblock %}

{% block content %}
     <div class="panel-body ">
           <div>
                            <a href="/add_questionnaire/"><button class="btn btn-success">添加</button></a>
                            <table class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>调查问卷名称</th>
                                    <th>调查问卷班级</th>
                                    <th>参与人数</th>
                                    <th>问卷选项</th>
                                    <th>调查地址</th>
                                    <th>查看评分</th>
                                    <th>操作</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% for questionnaire in questionnaire_list %}
                                    <tr>

                                        <td><a href="">{{ questionnaire.title }}</a></td>
                                        <td>{{ questionnaire.cls.title }}</td>
                                        <td>{{ questionnaire.stu_num }}/{{ questionnaire.cls.student_set.all.count }}</td>
                                        <td><a href="/edit_questionnaire/{{ questionnaire.id }}/">编辑问卷</a></td>
                                        <td>
                                            <a href="/student/evaluate/{{ questionnaire.id }}/{{ questionnaire.cls.id }}/">/student/evaluate/{{ questionnaire.id }}/{{ questionnaire.cls.id }}/</a>
                                        </td>
                                        <td><a href="">查看评分</a></td>
                                        <td><a href="">删除</a></td>
                                    </tr>
                                {% endfor %}


                                </tbody>
                            </table>
                        </div>
     </div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body style="background-color: #f8f8f8">

<div class="container   col-md-4 col-lg-offset-4 ">

    <div class="panel panel-info " style="margin-top: 100px">
        <div class="panel-heading" style="padding: 5px 0">
            <h4 class="text-center">请登录</h4>
        </div>
        <div class="row">
            <div class="panel-body col-md-10 col-md-offset-1">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group user">
                        <label for="exampleInputEmail1">用户名:</label>
                        <input type="text" class="form-control" id="username" placeholder="username">
                        <span id="helpBlock2" class="help-block"></span>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">密码:</label>
                        <input type="password" class="form-control" id="password" placeholder="password">
                        <span id="helpBlock3" class="help-block"></span>
                    </div>


                    <div class="form-group">
                        <span class="failed"></span>
                    </div>
                    <div class="form-group col-lg-offset-4 col-md-4">
                        <input type="button" value="登&nbsp;&nbsp;录" class="form-control btn-primary" id="subBtn">

                        <div id="popup-captcha"></div>

                        <span class="error"></span>

                    </div>

                </form>
                <div class="from-group">
                    <span class="form-group pull-right"><span>还没有账号？<a href="/register/">点击注册</a></span></span>

                </div>
            </div>

        </div>
    </div>

</div>
<script src="/static/js/jquery-3.2.1.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
{#<script src="/static/js/login.js"></script>#}
<script src="/static/js/student_login.js"></script>
</body>
</html>

templates/score.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/score.css">
</head>
<body>
<div class="container">
    <form method="post" novalidate>
        {% csrf_token %}
        {% for fd in form %}
            <div>
            <p>{{ forloop.counter }}：{{ fd.label }}{{ fd.errors.0 }}</p>
            {{ fd }}
            </div>
            <hr>
        {% endfor %}
        <button type="submit" class="btn btn-success">提交</button>
    </form>
</div>
</body>
</html>